# Generated by Django 5.2.3 on 2025-06-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
